config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
}

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}

  root to: "public/homes#top"
  get "/home/about" =>"public/homes#about" ,as: "about"

  namespace :admin do
    root to: "homes#top"
    get "admin" => "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  scope module: :public  do
    resources :items, only: [:show, :index]
    delete "cart_items/all_destroy" => "cart_items#all_destroy"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new, :create, :index, :show]

    get "customers/my_page" => "customers#show"
    get "customers/informetion/edit" => "customers#edit"
    patch "customers/informetion" => "customers#update"
    get "customers/quit" => "customers#quit"
    patch "customers/leave" => "customers#leave"
  end

  end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if  @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :admin_new
    end
  end

  def show
    @item = Item.new
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :admin_edit
    end
  end

private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>商品編集</h1>
        <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
        <table>
          <tr>
            <th>商品画像</th>
            <th><%= f.file_field :image, accept: "image/*" %></th>
          </tr>

          <tr>
            <th>商品名</th>
            <th><%= f.text_field :name %></th>
          </tr>

          <tr>
            <th>商品説明</th>
            <th><%= f.text_area :introduction %></th>
          </tr>

          <tr>
            <th>税込価格</th>
            <th><%= f.text_field :price %>円</th>
          </tr>
        </table>

      <div class="actions">
        <%= f.submit "設定を保存", class: 'btn btm-sm btn-success' %>
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="col-md-8 offset-md-1">
    <div class="row">
    <h2>商品一覧</h2>
    <h6><%= link_to "商品新規登録", new_admin_item_path %></h6>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>商品イメージ</th>
            <th>商品名</th>
            <th>税抜き価格</th>
          </tr>
        </thead>

        <tbody>
            <% @items.each do |item| %>
          <tr>
            <td>
              <%= image_tag item.image, size: "100x100" %>
            </td>
            <td>
              <%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
              <% end %>
            </td>
            <td>
              <%= item.price %>
            </td>
          </tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>
<%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>商品新規登録</h1>
        <%= form_with model: @item, url:'/admin/items' do |f| %>

        <table>
          <tr>
            <th>商品画像</th>
            <th><%= f.file_field :image, accept: "image/*" %></th>
          </tr>

          <tr>
            <th>商品名</th>
            <th><%= f.text_field :name %></th>
          </tr>

          <tr>
            <th>商品説明</th>
            <th><%= f.text_area :introduction %></th>
          </tr>

          <tr>
            <th>税込価格</th>
            <th><%= f.text_field :price %>円</th>
          </tr>
        </table>

      <div class="actions">
        <%= f.submit "新規登録", class: 'btn btm-sm btn-success' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/items/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h2>商品詳細</h2>
    </div>
    <div class="row">
    <div class="col-md-3">
        <%= image_tag @item.image, size: "200x200" %>
     </div>

    <div class="col-md-8 offset-md-1">
      <table>
        <tbody>
          <tr>
            <th>商品名</th>
            <td><%= @item.name %></td>
          </tr>

            <tr>
              <th>商品説明</th>
              <td><%= @item.introduction %></td>
            </tr>

          <tr>
            <th>税込価格（税抜き価格）</th>
            <td><%= (@item.price * 1.1).floor %> <%# 税込 %>
                (<%= @item.price %>)円 <%# 税抜き %>
            </td>
          </tr>

          <td class="btn btm-sm btn-success">
              <%= link_to "編集する", edit_admin_item_path(@item) %>
          </td>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>