config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
}

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}

  root to: "public/homes#top"
  get "/home/about" =>"public/homes#about" ,as: "about"

  namespace :admin do
    root to: "homes#top"
    get "admin" => "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  scope module: :public  do
    resources :items, only: [:show, :index]
    delete "cart_items/all_destroy" => "cart_items#all_destroy"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new, :create, :index, :show]

    get "customers/my_page" => "customers#show"
    get "customers/informetion/edit" => "customers#edit"
    patch "customers/informetion" => "customers#update"
    get "customers/quit" => "customers#quit"
    patch "customers/leave" => "customers#leave"
  end

  end

app/models/customer.rb
class Customer < ApplicationRecord

 has_many :cart_items
 has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
     @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

private
  def customer_params
  	params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :postal_code, :address, :phone_numbar)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
<h3><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h3>
  </div>
  <div class="row">
  <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
  <table>
    <tr>
        <th>会員ID</th>
        <th><%= @customer.id %></th>
    </tr>

  <tr>
    <th>氏名</th>
    <th>(姓)<%= f.text_field :last_name, autofocus: true, autocomplete: "name" %></th>
    <th>(名)<%= f.text_field :first_name, autofocus: true, autocomplete: "name" %></th>
  </tr>

  <tr>
    <th>フリガナ</th>
    <th>(セイ)<%= f.text_field :last_name_kana, autofocus: true, autocomplete: "name" %></th>
    <th>(メイ)<%= f.text_field :first_name_kana, autofocus: true, autocomplete: "name" %></th>
  </tr>

  <tr>
    <th>郵便番号</th>
    <th><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %></th>
  </tr>

  <tr>
    <th>住所</th>
    <th><%= f.text_field :address, autofocus: true, autocomplete: "address" %></th>
  </tr>

  <tr>
    <th>電話番号</th>
    <th><%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %></th>
  </tr>

  <tr>
    <th>メールアドレス</th>
    <th><%= f.text_field :email, autofocus: true, autocomplete: "email" %></th>
  </tr>

  <tr>
    <th>会員ステータス</th>
    <th>
      <% if @customer.is_deleted? %>
            退会
        <% else %>
            有効
        <% end %>
    </th>
  </tr>
</table>
<div class="actions" >
<%= f.submit "変更を保存", class: 'btn btn-success' %>
<% end %>
</div>
</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
<h2>会員一覧</h2>
</div>
<div class="row">
  <div class="offset-md-1">
  <table class="table">
  <head>
  <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
  </tr>
  </head>

  <body>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>

        <td>
          <%= link_to admin_customer_path(customer.id) do %>
          <%= customer.last_name + customer.first_name %>
          <% end %>
        </td>

        <td><%= customer.email %></td>

        <td>
         <% if customer.is_deleted %>
            退会
         <% else %>
            有効
         <% end %>
        </td>
      </tr>
      <% end %>
  </body>
  </table>
  <%= paginate @customers %>
  </div>
  </div>
  </div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
<h3><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h3>
  </div>
  <div class="row">
  <table>
  <tr>
    <th>会員ID</th>  <td><%= @customer.id %></td>
  </tr>

  <tr>
    <th>氏名</th>  <td><%= @customer.last_name + @customer.first_name %></td>
  </tr>

  <tr>
    <th>フリガナ</th>  <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
  </tr>

  <tr>
    <th>郵便番号</th>  <td><%= @customer.postal_code %></td>
  </tr>

  <tr>
  　 <th>住所</th>  <td><%= @customer.address %></td>
  </tr>

  <tr>
    <th>電話番号</th>  <td><%= @customer.telephone_number %></td>
  </tr>

  <tr>
    <th>メールアドレス</th>  <td><%= @customer.email %></td>
  </tr>

  <tr>
    <th>会員ステータス</th>
    <td>
      <% if @customer.is_deleted? %>
            退会
        <% else %>
            有効
        <% end %>
    </td>
  </tr>

  <tr>
    <th><%= link_to "編集する", edit_admin_customer_path(@customer), class: 'btn btn-success' %></th>
    <th><%= link_to "注文履歴一覧を見る", admin_order_path(@customer), class: 'btn btn-primary' %></th>
  </tr>
  </table>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>